### ISSUE TITLE
This project is dead?

### ISSUE THREAD

**Issue by blling** [tuddman/axon-guice#4]
Is this repo deprecated?

**Comment by tuddman** [comment]
yes. I have not used this library in some years.

dependencies may likely be out of date.

**Comment by blling** [comment]
Do you still use AxonFramework?

**Comment by tuddman** [comment]
I took the design principles inherent in CQRS, but have implemented much more elegantly in Clojure.

No, I no longer use AxonFramework (and limiting exposure to Java, generally) for any production systems.
